frontend:
  angular-url: "http://localhost:4200"

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
